Repository 4anghyeon/poll-in-love, pull requests merged in 2023-12, with the labels that each got.

#7 UI/enroll 50%
  package.json
  public/manifest.json
  src/App.jsx
  src/assets/fonts/font.css
  src/components/Enroll/SubmitPoll/SubmitPollContainer.jsx
  src/components/Enroll/WritePoll/CustomSelect.jsx
  src/components/Enroll/WritePoll/PollFormBox.jsx
  src/components/Enroll/WritePoll/UserAnswerFormBox.jsx
  src/components/Enroll/WritePoll/UserAnswerInputRow.jsx
  src/components/Enroll/WritePoll/WritePollContainer.jsx
  src/components/Layout/Footer.jsx
  src/index.js
  src/pages/EnrollPage.jsx
  src/shared/AppRouter.jsx
  src/styles/CommonStyles.jsx
  src/styles/GlobalStyles.jsx
  yarn.lock
Labels: 버그, 수정, 설정, UI

#8 add: 설문 등록 페이지 질문 제출 UI (#4)
  src/components/Common/Select.jsx
  src/components/Enroll/SubmitPoll/AdditionalInfoBox.jsx
  src/components/Enroll/SubmitPoll/SubmitPollContainer.jsx
  src/components/Enroll/SubmitPoll/ThumbnailBox.jsx
  src/components/Enroll/WritePoll/PollFormBox.jsx
  src/pages/EnrollPage.jsx
Labels: UI

#12 add: 설문 등록 페이지 질문 제출 기능 개발 (#9)
  src/api/enroll.js
  src/components/Enroll/SubmitPoll/AdditionalInfoBox.jsx
  src/components/Enroll/SubmitPoll/SubmitPollContainer.jsx
  src/components/Enroll/WritePoll/PollFormBox.jsx
  src/components/Enroll/WritePoll/UserAnswerFormBox.jsx
  src/components/Enroll/WritePoll/UserAnswerInputRow.jsx
  src/components/Enroll/WritePoll/WritePollContainer.jsx
  src/hooks/useChangeAdditionalInfo.js
  src/pages/EnrollPage.jsx
  src/redux/modules/enrollSlice.js
  src/redux/store.js
  src/styles/CommonStyles.jsx
Labels: 기능

#11 style: Home 퍼블리싱, 반응형구현 (#2)
  src/assets/images/whitePick.png
  src/components/Home/Home.jsx
  src/components/Layout/Layout.jsx
  src/shared/mock.js
  src/utils/defaultValue.js
Labels: UI

#16 fix: 설문 참여 페이지 고장 수정 (#15)
  src/components/Enroll/SubmitPoll/ThumbnailBox.jsx
  src/components/Layout/Layout.jsx
  src/pages/EnrollPage.jsx
Labels: 버그, UI

#21 fix: 메인페이지 link 추가 및 mokdata수정 (#20)
  src/components/Home/Home.jsx
  src/components/Shop/Shop.jsx
  src/pages/ShopPage.jsx
  src/shared/AppRouter.jsx
  src/shared/mock.js
  src/styles/GlobalStyles.jsx
Labels: 수정

#23 fix: 메인페이지 link 수정
  src/components/Home/Home.jsx
Labels: 수정

#25 [Feature/Home] firebase 연동
  package.json
  src/api/enroll.js
  src/api/items.js
  src/api/polls.js
  src/components/Enroll/SubmitPoll/SubmitPollContainer.jsx
  src/components/Home/Home.jsx
  src/shared/mock.js
  yarn.lock
Labels: 기능, 설정

#26 Feature/poll 설문 기능 개발 완료
  src/api/participants.js
  src/api/polls.js
  src/components/Enroll/SubmitPoll/AdditionalInfoBox.jsx
  src/components/Home/Home.jsx
  src/components/Poll/QuestionBox.jsx
  src/pages/PollPage.jsx
Labels: 기능

#30 bugfix: 설문 페이지 이동시 오류 수정 (#28)
  src/api/polls.js
  src/pages/PollPage.jsx
  src/shared/AppRouter.jsx
Labels: 버그

#32 [Fix/enroll] 설문 등록 페이지 개선
  src/api/polls.js
  src/components/Common/Select.jsx
  src/components/Enroll/SubmitPoll/AdditionalInfoBox.jsx
  src/components/Enroll/SubmitPoll/SubmitPollContainer.jsx
  src/components/Enroll/SubmitPoll/ThumbnailBox.jsx
  src/components/Enroll/WritePoll/PollFormBox.jsx
  src/components/Enroll/WritePoll/UserAnswerInputRow.jsx
  src/components/Enroll/WritePoll/WritePollContainer.jsx
  src/pages/EnrollPage.jsx
  src/redux/modules/enrollSlice.js
  src/utils/toast-option.js
Labels: 기능

#33 [UI/Shop] 포인트 상점 퍼블리싱
  package.json
  src/components/Home/Home.jsx
  src/components/Shop/Shop.jsx
  yarn.lock
Labels: UI

#36 update: 설문 참여시 포인트 증가 (#22)
  src/api/users.js
  src/hooks/useChangeAdditionalInfo.js
  src/pages/PollPage.jsx
Labels: 기능

#35 update: 설문 등록시 자성자 이메일/닉네임 추가 (#27)
  src/pages/EnrollPage.jsx
Labels: 기능

#37 update: UI/ UX 개선 (#29)
  src/pages/PollPage.jsx
Labels: UI

#43 add: 엑셀 다운로드 기능 개발 (#38)
  package.json
  src/utils/helper.js
  yarn.lock
Labels: 기능

#50 [Feature/Shop] 카테고리별 정렬
  src/components/Home/Home.jsx
  src/components/Shop/Shop.jsx
Labels: 기능, 수정

#51 [Feature/Shop] 구매 로직
  src/api/users.js
  src/components/Shop/Shop.jsx
Labels: 기능

#52 fix: 참여자 포인트 획득 오류 수정 (#47)
  src/components/Enroll/SubmitPoll/AdditionalInfoBox.jsx
  src/pages/SignUpPage.jsx
  src/utils/defaultValue.js
Labels: 수정

#60 bugfix: 구글 로그인시 firebase에 유저 정보 계속 추가 현상 수정 (#58)
  src/api/users.js
  src/pages/LoginPage.jsx
Labels: Merge

#61 update: 설문 조사 데이터 다운로드 기능 구현 (#41)
  src/pages/MyPage.jsx
  src/utils/helper.js
  src/utils/toast-option.js
Labels: 기능, Merge

#66 add: 아이템 구매시 sale 증가 (#65)
  src/api/items.js
  src/components/Shop/Shop.jsx
Labels: 기능, Merge

#70 update: 메인페이지 정렬 및 한정된 수로 보이기
  src/components/Home/Home.jsx
Labels: 기능

#72 fix: home 화면에서 마감 기한 지난 데이터는 안나오게 (#71)
  src/api/polls.js
  src/components/Home/Home.jsx
Labels: Merge

#80 Feature/home search
  package.json
  src/components/Home/Home.jsx
  yarn.lock
Labels: 버그, 기능, UI

#82 UI,fix/home : 반응형수정
  src/components/Home/Home.jsx
  src/components/Layout/Header.jsx
  src/components/Shop/Shop.jsx
Labels: 수정

#84 bugfix: 설문 참여 조건 필터링 (#22)
  src/components/Layout/Header.jsx
  src/components/Poll/QuestionBox.jsx
  src/pages/LoginPage.jsx
  src/pages/PollPage.jsx
  src/shared/AppRouter.jsx
  src/utils/toast-option.js
Labels: Merge

#88 Fix/home 성별, 연령대 추가
  src/components/Home/Home.jsx
Labels: 수정

#90 fix: 다른페이지에서 홈으로 올경우 무한렌더링 이슈 해결(#89)
  src/components/Home/Home.jsx
Labels: 버그

#91 bugfix: 로그아웃시 로그인 후 이용해주세요 팝업 버그 수정 (#83)
  src/components/Layout/Header.jsx
  src/pages/EnrollPage.jsx
Labels: 버그, Merge

#95 add: top 버튼 및 기능 추가(#93)
  src/components/Home/Home.jsx
Labels: 기능

#96 ui: 반응형 추가 및 일부 데이터 조정
  src/pages/EnrollPage.jsx
  src/pages/MyPage.jsx
  src/pages/PollPage.jsx
  src/pages/SignUpPage.jsx
Labels: UI, Merge

#98 bugfix: 엑셀 다운로드 오류 수정 (#97)
  src/utils/helper.js
Labels: Merge

#101 add: 광고보고 포인트 얻기 기능 추가
  package.json
  src/App.jsx
  src/api/youtube.js
  src/components/Layout/Header.jsx
  src/components/Shop/AdModal.jsx
  src/components/Shop/Shop.jsx
  src/hooks/useUpdatePoint.js
  src/pages/MyPage.jsx
  yarn.lock
Labels: Merge
